world:
    base_path: "/tmp/worlds"
    prototype_path: "config/flash_prototype"
    nexus_endpoint: "worldhub.dubitplatform.com:1937"
bitly:
    username: dubitplatform
    api_key: R_a42fdf5201323fb9e4b2683f9049e9ff